version: '3.3'
services:
  php:
    image: php:7.4.30-fpm
    volumes:
      - ./project:/var/www/html
      - ./php/php-fpm.conf:/usr/local/etc/php/php-fpm.conf
    networks:
        - lnmp
    user: root
    privileged: true
    depends_on:
        - mysql
        - redis
    ports:
        - 9000:9000
    environment:
        - TZ=Asia/Shanghai
  mysql:
    container_name: mysql
    command:
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    image: mysql:5.6
    networks:
        - lnmp
    ports:
      - 3307:3306
    environment:
            - "TZ=Asia/Shanghai"
            - "MYSQL_PASSWORD=123456"
            - "MYSQL_ROOT_PASSWORD=123456"
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
      - ./mysql/db:/docker-entrypoint-initdb.d:ro
  redis:
    image: redis:5.0.0
    container_name: redis
    command: redis-server
    networks:
        - lnmp
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    ports:
      - 8081:80
    networks:
        - lnmp
    depends_on:
        - php
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./project:/var/www
networks:
    lnmp: